Replace stdout / stderr with commons-logging
seeburger-ag/seeburger-vfs2 pull request #5
Opened 2022-08-23 09:07 UTC by svogt

Use logging instead of stdout / stderr

2022-08-23 13:00 UTC, ecki requested changes
Tanks, looks good. I would just add a log message to the ignored exception while we are at it.

2022-08-23 13:00 UTC, ecki commented on vfs2provider-jdbctable/src/main/java/com/seeburger/vfs2/provider/jdbctable/JdbcTableRowFile.java
> +                LOG.warn(e);
I would use („Ignoring exception while cleaning up connection“, e)“ or a similar message.

2022-08-23 13:00 UTC, ecki commented on vfs2provider-jdbctable/src/main/java/com/seeburger/vfs2/provider/jdbctable/JdbcDialectBase.java
> +import org.apache.commons.logging.Log;
Yes, seems ok, commons logging is used in VFS as well.

2022-08-23 19:22 UTC, svogt commented on vfs2provider-jdbctable/src/main/java/com/seeburger/vfs2/provider/jdbctable/JdbcTableRowFile.java
> +                LOG.warn(e);
done

2022-08-24 12:03 UTC, ecki approved these changes
Danke, sieht gut aus.

2022-08-24 12:03 UTC, merged